apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels: { app: payments }
spec:
  replicas: 1
  selector: { matchLabels: { app: payments } }
  template:
    metadata: { labels: { app: payments } }
    spec:
      imagePullSecrets:
      - name: jfrog-secret
      containers:
      - name: payments
        image: jfrog2026.jfrog.io/microservices/project/payments:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        readinessProbe:
          httpGet: { path: /health, port: 3004 }
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 3004 }
          initialDelaySeconds: 10
          periodSeconds: 20
